import Head from "next/head";
import Image from "next/image";

import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Technologies from "../components/Technologies";
import ContactMe from "../components/ContactMe";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className="h-screen  overflow-y-scroll scrollbar-thin scrollbar-thumb-[#373446] scrollbar-hide vs:scrollbar-default">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#10101a]  ">
        {/* Hero */}
        <Hero />
        {/* Technologies */}
        <Technologies />
        {/* Projects */}
        <Projects />
        {/* ContactMe */}
        <ContactMe />
        {/* Footer */}
        <Footer />
      </div>
    </div>
  );
}
