import Head from "next/head";
import Image from "next/image";

import Hero from "../components/Hero";
import Projects from "../components/Projects";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#10101a] ">
        {/* Hero */}
        <Hero />
        {/* Projects */}
        <Projects />
        {/* Projects */}
      </div>
    </div>
  );
}
